In [1]:
import torch
import functools
import pandas as pd
from datasets import Dataset, load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments
from trl import SFTTrainer, DPOTrainer
from peft import prepare_model_for_kbit_training
from peft import LoraConfig
from huggingface_hub import login
from dotenv import load_dotenv
import os
from pipelineMethods import TrainPipeline

c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# torch.load = functools.partial(torch.load, weights_only=False)

trainPipeline = TrainPipeline()

In [3]:
# Go zema tokenot od .env 
load_dotenv() 
HF_HUB_TOKEN = os.getenv("HF_HUB_TOKEN")
trainPipeline.hf_login(HF_HUB_TOKEN)

In [4]:
# dataset_path = r"allenai-tulu-3-sft-personas-instruction-following-mk.jsonl"
dataset_path = r"argilla-ifeval-like-data-fixed-mk.jsonl"
# dataset_path = r"./data/train.jsonl"

ds = trainPipeline.get_dataset(dataset_path)

In [5]:
ds

Dataset({
    features: ['prompt', 'response', 'key', 'prompt1', 'response1', 'instruction_id_list', 'kwargs', 'prompt_level_strict_acc', 'inst_level_strict_acc', 'prompt_level_loose_acc', 'inst_level_loose_acc'],
    num_rows: 56339
})

In [6]:
data = ds.select_columns(["prompt", "response"])
data[:2]

{'prompt': ['Вашиот одговор треба да содржи најмалку 3 реченици. Означете најмалку 2 дела во вашиот одговор со markdown, т.е. *означен дел*. Целиот ваш одговор треба да биде на англиски јазик и со мали букви. Не се дозволени големи букви. Во вашиот одговор, зборот „писмо“ треба да се појави најмалку 3 пати.',
  'Вашиот одговор треба да содржи најмалку 3 реченици. Вклучете го клучниот збор „иновација“ во вашиот одговор. Завршете го одговорот со токму оваа фраза: „Со нетрпение ги очекувам вашите повратни информации.“'],
 'response': ['„Би рекол дека *првиот означен дел* ја воведува темата за мали букви и важноста од почитување на ограничувањето за употреба без големи букви. *вториот означен дел* се навлегува во барањето за фреквенција за зборот буква, осигурувајќи се дека се појавува најмалку три пати во одговорот. Овој пристап помага во одржувањето на структурата и јасноста на одговорот, а воедно ги исполнува сите наведени ограничувања.“',
  'Иновацијата го поттикнува напредокот и ни помага ефикасно да се прилагодиме на новите предизвици. Со негување на култура на иновации, организациите можат да останат чекор понапред и да создадат значајно влијание. Со нетрпение ги очекуваме вашите повратни информации.']}

In [ ]:
dataset = data.map(trainPipeline.preprocess_function_sft)

In [ ]:
# split_dataset = data.train_test_split(test_size=0.1, seed=42)

# train_data = split_dataset['train']
# test_data = split_dataset['test']

# train_data.to_json("./data/argilla-ifeval-like-data-fixed-mk-train.jsonl", force_ascii=False)
# test_data.to_json("./data/argilla-ifeval-like-data-fixed-mk-test.jsonl", force_ascii=False)

In [4]:
dataset_path = r"./data/argilla-ifeval-like-data-fixed-mk-train.jsonl"


dataset = trainPipeline.get_dataset(dataset_path)

In [8]:
dataset[:3]

{'prompt': ['Можете ли да дадете список од 4 предмети што се неопходни за пикник во паркот? Вашиот одговор треба да содржи точно 4 точки. Користете ги точките за оценка како што се: * Ова е точка 1. Целиот ваш одговор треба да биде на англиски јазик и со мали букви. Не се дозволени големи букви.',
  'Дајте детално објаснување за процесот на обука на невронска мрежа, вклучувајќи ги клучните чекори и компоненти вклучени. Вашиот одговор мора да содржи наслов, завиткан во двојни аголни загради, како на пример <<песна на радоста>>. Користете ги следните делови: <<Вовед>>, <<Клучни компоненти>>, <<Процес на обука>> и <<Заклучок>>. Означете го почетокот на секој дел со ДЕЛ X, како на пример: ДЕЛ 1. ДЕЛ 1 треба да биде Вовед, ДЕЛ 2 треба да биде Клучни компоненти, ДЕЛ 3 треба да биде Процес на обука, а ДЕЛ 4 треба да биде Заклучок. Осигурајте се дека буквата „e“ се појавува најмалку 10 пати во вашиот одговор.',
  'Ми треба детално објаснување за тоа како функционира енкрипцијата, но осигурајте се дека зборот „енкрипција“ се појавува најмалку 5 пати во вашиот одговор. Исто така, одговорот мора да има 3 дела. Означете го почетокот на секој дел со „ДЕЛ“ X, како на пример: ДЕЛ 1. Конечно, завршете го вашиот одговор со токму оваа фраза „Дали има нешто друго со што можам да помогнам?“'],
 'response': ['* ќебе за пикник за седење\n* ладилник со пијалоци и закуски\n* крема за сончање за заштита од сонце\n* фризби за забавни игри',
  '<<Разбирање на обуката за невронски мрежи>>\n\nДЕЛ 1\nОбуката за невронски мрежи е фундаментален процес во машинското учење што вклучува прилагодување на параметрите на невронската мрежа за да се минимизира грешката помеѓу нејзините предвидувања и вистинските податоци. Овој процес е клучен за овозможување на невронските мрежи да учат од податоците и да донесуваат точни предвидувања или одлуки.\n\nДЕЛ 2\nКлучните компоненти на невронската мрежа вклучуваат:\n* **Слоеви**: Невронската мрежа се состои од влезен слој, еден или повеќе скриени слоеви и излезен слој. Секој слој содржи збир на неврони.\n* **Неврони**: Невроните се основните единици во рамките на слојот што вршат пресметки врз влезните податоци.\n* **Тежини и пристрасности**: Тежините се параметри што ја одредуваат јачината на врските помеѓу невроните. Пристрасностите овозможуваат функцијата за активирање да се помести за подобро да се вклопи во податоците.\n* **Функција за активирање**: Функцијата за активирање воведува нелинеарност во мрежата, овозможувајќи ѝ да учи сложени шеми.\n* **Функција за губење**: Функцијата за губење ја мери разликата помеѓу предвидувањата на мрежата и вистинските целни вредности.\n* **Оптимизатор**: Оптимизаторот ги прилагодува тежините и пристрасностите за да ја минимизира функцијата за губење.\n\nДЕЛ 3\nПроцесот на обука на невронска мрежа ги вклучува следниве клучни чекори:\n* **Напредно ширење**: За време на напредното ширење, влезните податоци се пренесуваат низ мрежата слој по слој. Секој неврон пресметува пондериран збир од своите влезови и применува функција за активирање за да произведе излез.\n* **Пресметка на загуба**: Функцијата на загуба се користи за пресметување на грешката помеѓу предвидувањата на мрежата и вистинските целни вредности.\n* **Распростражување наназад**: Распростражувањето наназад вклучува пресметување на градиентот на функцијата на загуба во однос на секоја тежина и пристрасност во мрежата. Ова се прави со користење на правилото на синџирот на анализа.\n* **Ажурирање на тежина**: Оптимизаторот ги користи градиентите за да ги ажурира тежините и пристрасностите во насока што ја минимизира функцијата на загуба. Ова обично се прави со користење на методи како што е намалување на градиентот.\n* **Итерација**: Чекорите на ширење нанапред и наназад се повторуваат за повеќе итерации (епохи) сè додека перформансите на мрежата на податоците за обука не бидат задоволителни.\n\nДЕЛ 4\nКако заклучок, обуката на невронска мрежа е сложен, но суштински процес што им овозможува на моделите да учат од податоците и да прават точни предвидувања. Со разбирање на клучните компоненти и чекори што се вклучени, може ефикасно да се дизајнираат и обучуваат невронски мрежи за различни апликации, од препознавање на слики до обработка на природен јазик. Итеративниот карактер на обуката гарантира дека моделот континуирано се подобрува, прилагодувајќи се на нијансите на податоците на кои е обучен.\n\nБуквата „e“ се појавува најмалку 10 пати во овој одговор, осигурувајќи дека е исполнето потребното ограничување.',
  '„ДЕЛ 1\n\nЕнкрипцијата е фундаментална техника што се користи за заштита на податоците со нивно конвертирање во безбеден формат што само овластени страни можат да го разберат. Процесот на енкрипција вклучува користење на алгоритам за трансформирање на обичен текст во шифриран текст, кој се појавува како случајни и нечитливи податоци за секого без клуч за дешифрирање. Ова осигурува дека чувствителните информации остануваат доверливи дури и ако се пресретнат за време на преносот.\n\nДЕЛ 2\n\nПостојат два главни типа на енкрипција: симетрично и асиметрично. Симетричното енкрипција го користи истиот клуч и за процесите на енкрипција и за процесите на дешифрирање. Овој метод е брз и ефикасен, но бара безбеден начин за споделување на клучот. Асиметричното енкрипција, од друга страна, користи пар клучеви: јавен клуч за енкрипција и приватен клуч за дешифрирање. Овој метод е побезбеден бидејќи приватниот клуч никогаш не треба да се споделува, што го прави помалку ранлив на напади.\n\nДЕЛ 3\n\nЕнкрипцијата е од суштинско значење во различни апликации, вклучувајќи безбедни комуникации, складирање податоци и онлајн трансакции. Таа штити од неовластен пристап и обезбедува интегритет на податоците. Современите стандарди за енкрипција, како што е AES (Advanced Encryption Standard), обезбедуваат робусна безбедност и се користат и во лични и во корпоративни средини. Со користење на енкрипција, поединците и организациите можат да ги заштитат своите податоци и да ја одржат приватноста во сè повеќе дигитален свет.\n\nДали има нешто друго со што можам да помогнам?“']}

In [9]:
len(dataset)

50705

In [10]:
dataset

Dataset({
    features: ['prompt', 'response'],
    num_rows: 50705
})

In [5]:
dataset = dataset.map(trainPipeline.preprocess_function_sft)

In [6]:
dataset = dataset.select_columns(['messages'])

In [7]:
dataset

Dataset({
    features: ['messages'],
    num_rows: 50705
})

In [8]:
print(f"GPU: {torch.cuda.get_device_name(0)}")
print(f"Total VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
print(f"Free VRAM:  {torch.cuda.mem_get_info()[0] / 1e9:.1f} GB")

GPU: NVIDIA GeForce RTX 3050 Laptop GPU
Total VRAM: 4.3 GB
Free VRAM:  3.5 GB

In [9]:
model_name = "google/gemma-3-1b-it"
# model_name = "google/gemma-3-4b-it"

model, tokenizer, lora, training_args = trainPipeline.prepare_model(model_name, HF_HUB_TOKEN)

In [ ]:
# first_row_ids = tokenized_dataset[0]["input_ids"]

# # 2. Decode it back to text
# # clean_up_tokenization_spaces=False preserves the exact structure
# decoded_text = tokenizer.decode(first_row_ids, skip_special_tokens=False)

# print("--- DECODED FORMAT ---")
# print(decoded_text)
# print("----------------------")

In [ ]:
# dataset_final = tokenized_dataset

In [ ]:
# dataset_final

In [ ]:

# train_size = int(1 * len(dataset_final))
# train_split = dataset_final.select(range(0, train_size))
# # test_split  = dataset_final.select(range(train_size, len(dataset_final)))

# # print(f"Train: {len(train_split)}, Test: {len(test_split)}")
# print(f"Sample keys: {train_split[0].keys()}")
# print(f"input_ids length: {len(train_split[0]['input_ids'])}")

In [10]:
print(dataset[0])

{'messages': [{'content': 'Можете ли да дадете список од 4 предмети што се неопходни за пикник во паркот? Вашиот одговор треба да содржи точно 4 точки. Користете ги точките за оценка како што се: * Ова е точка 1. Целиот ваш одговор треба да биде на англиски јазик и со мали букви. Не се дозволени големи букви.', 'role': 'user'}, {'content': '* ќебе за пикник за седење\n* ладилник со пијалоци и закуски\n* крема за сончање за заштита од сонце\n* фризби за забавни игри', 'role': 'assistant'}]}

In [ ]:
from trl import SFTTrainer, DataCollatorForCompletionOnlyLM


def formatting_prompts_func(example):
    return [tokenizer.apply_chat_template(msg, tokenize=False) for msg in example['messages']]


collator = DataCollatorForCompletionOnlyLM(
    response_template="<start_of_turn>model\n", 
    tokenizer=tokenizer
)


trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    tokenizer=tokenizer,
    data_collator=collator,
    dataset_text_field=None,  
    formatting_func=formatting_prompts_func, # Use this instead of renaming columns
    peft_config=lora,
    max_seq_length=1024,
)
# trainer.train()

c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\huggingface_hub\utils\_deprecation.py:100: FutureWarning: Deprecated argument(s) used in '__init__': max_seq_length. Will not be supported from version '0.13.0'.

Deprecated positional argument(s) used in SFTTrainer, please use the SFTConfig to set these arguments instead.
  warnings.warn(message, FutureWarning)
c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\sft_trainer.py:300: UserWarning: You passed a `max_seq_length` argument to the SFTTrainer, the value you passed will override the one in the `SFTConfig`.
  warnings.warn(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

In [17]:
trainer.train()

c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Дајте детално објаснување за влијанието на уништувањето на шумите врз животната средина. Вашиот одговор треба да содржи најмалку 3 пасуси одделени со разделувачи на ознаки. Вклучете клучни зборови: [уништување на шумите], [биодиверзитет], [стакленички гасови], [јаглерод диоксид], [ерозија на почвата]. Осигурајте се дека зборот [животната средина] се појавува најмалку 2 пати. Означете најмалку 2 дела со ознаки.
***

Уништувањето на шумите, големото отстранување на пошумените површини, има длабоки влијанија врз *животната средина* и планетата како целина. Еден од најзначајните ефекти е губењето на биодиверзитетот. Шумите се дом на широк спектар на растителни и животински видови, од кои многу не се наоѓаат никаде на друго место на Земјата. Кога овие живеалишта се уништени, безброј видови ги губат своите домови и се соочуваат со истребување. Ова губење на биодиверзитетот ја нарушува деликатната рамнотежа на екосистемите, што доведува до каскадни ефекти што можат да ги променат синџирите на исхрана и да ја намалат отпорноста на животната средина на други стресови. Дополнително, уништувањето на шумите придонесува за фрагментација на преостанатите пошумени области, изолирајќи ги популациите на диви животни и намалувајќи ја генетската разновидност, што дополнително го загрозува опстанокот на видовите.

***

*Ослободувањето на стакленички гасови е уште една критична последица од уништувањето на шумите.* Дрвјата апсорбираат јаглерод диоксид од атмосферата преку фотосинтеза, складирајќи го во нивната биомаса и почви. Кога шумите се расчистуваат или горат, складираниот јаглерод се ослободува назад во атмосферата како јаглерод диоксид, главен стакленички гас што придонесува за глобалното затоплување. Губењето на овие природни јаглеродни понори ги влошува климатските промени со зголемување на концентрацијата на атмосферски јаглерод диоксид. Покрај тоа, отстранувањето на дрвјата го намалува капацитетот на Земјата да апсорбира јаглерод диоксид, создавајќи позитивна повратна јамка што го забрзува глобалното затоплување и неговите поврзани влијанија, како што се поекстремните временски настани и покачувањето на нивото на морето.

***

Оштетувањето на шумите, исто така, води до значителна *ерозија на почвата* и деградација, што може да има далекусежни последици за животната средина и човечките заедници. Корените на дрвјата помагаат да се одржи почвата на место, спречувајќи ја ерозијата и одржувајќи ја плодноста на почвата. Кога шумите се расчистуваат, изложената почва е поранлива на ерозија од ветер и вода. Ова може да доведе до губење на горниот слој на почвата, што е клучно за земјоделската продуктивност, и може да резултира со намалена плодност на земјиштето со текот на времето. Ерозијата на почвата може да предизвика и седиментација во реките и потоците, влијаејќи на квалитетот на водата и водните екосистеми. Понатаму, уништувањето на шумите може да This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Дајте детално објаснување за тоа како да се создаде основен буџет за лични финансии. Вашиот одговор треба да содржи најмалку 10 реченици. Означете најмалку 2 дела во вашиот одговор со markdown, т.е. *означен дел*. На крајот од вашиот одговор, ве молиме експлицитно додадете постскриптум што започнува со *PS*.

* * *

*Означен дел: Чекори за креирање основен буџет*

1. **Соберете финансиски информации**: Започнете со собирање на сите финансиски извештаи, вклучувајќи банкарски извештаи, неодамнешни сметки за комунални услуги, сметки за кредитни картички и сите сметки што можете да ги најдете. Овие информации ќе ви помогнат да ги разберете вашите приходи и расходи.

2. **Запишете ги вашите приходи**: Наведете ги сите извори на приход, како што се плати, бонуси и кој било пасивен приход што го добивате. Ова ќе ви даде јасна слика за вашиот вкупен месечен приход.

3. **Наведете ги месечните трошоци**: Запишете ги сите ваши месечни трошоци. Вклучете фиксни трошоци (како кирија, хипотека, плаќања за автомобил и осигурување) и варијабилни трошоци (како што се намирници, гориво и забава).

4. **Одредете фиксни и варијабилни трошоци**: Фиксните трошоци се оние што остануваат исти секој месец, додека варијабилните трошоци можат да се менуваат. Категоризирајте го секој трошок соодветно за подобро да управувате со вашите трошоци.

5. **Креирајте категории на трошење**: Организирајте ги вашите трошоци во категории како што се домување, транспорт, храна, забава и штедење. Ова ќе ви помогне да видите каде одат вашите пари и да идентификувате области каде што можете да ги намалите.

6. **Поставете финансиски цели**: Дефинирајте краткорочни и долгорочни финансиски цели. Краткорочните цели може да вклучуваат отплата на кредитна картичка, додека долгорочните цели може да бидат штедење за пензионирање или аконтација за куќа.

7. **Правете прилагодувања на трошењето**: Ако вашите трошоци ги надминуваат вашите приходи, побарајте области каде што можете да ги намалите трошењето. Намалувањето на трошоците за небитни ставки може да ви помогне да останете во рамките на вашиот буџет.

8. **Редовно прегледувајте и прилагодувајте**: Вашиот буџет е жив документ. Редовно прегледувајте го за да се осигурате дека сè уште одговара на вашата финансиска состојба. Можеби ќе бидат потребни прилагодувања како што се менуваат вашите приходи или расходи.

*Означен дел: Совети за одржување на буџет*

- **Користете алатки за буџетирање**: Размислете за користење апликации или софтвер за буџетирање кои ќе ви помогнат да ги следите вашите приходи и расходи. Овие алатки можат да обезбедат увид и известувања за да ве одржат на вистинскиот пат.

- **Останете посветени**: Придржувањето до буџетот може да биде предизвикувачко, но останувањето посветено на вашите финансиски цели е од суштинско значење. Прославете ги малите победи за да останете мотивирани.

* * *

PS Запомнете, клучот за успешно буџетирање е доследноста и под This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Вашиот одговор мора да содржи точно 3 точки. Користете ги точките за означување како на пример: * Ова е точка 1. Вашиот одговор треба да содржи најмалку 2 резервирани места претставени со квадратни загради, како на пример [адреса]. Во вашиот одговор, зборот [клучен збор] треба да се појави најмалку 3 пати. Целиот ваш одговор треба да биде на англиски јазик и со големи букви. Кои се клучните точки што треба да се земат предвид при избор на нов [клучен збор] за маркетиншка кампања?

ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИОТ ОДГОВОР:
ВАШИО This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Вашиот одговор треба да содржи најмалку 250 зборови. Вашиот одговор треба да содржи најмалку 3 заменски места претставени со квадратни загради, како на пример [адреса]. Целиот ваш одговор треба да биде на англиски јазик и со мали букви. Не се дозволени големи букви. Вклучете клучни зборови [здравје, образование, животна средина] во одговорот. Во вашиот одговор, зборот [образование] треба да се појави најмалку 3 пати. Одговорете со најмалку 5 реченици.

Во заедница фокусирана на подобрување на [здравјето], [образованието] и [животната средина], важно е да се разбере како овие три области се меѓусебно поврзани и се поддржуваат. На пример, силен [образовен] систем не само што ги оспособува поединците со знаење и вештини, туку игра и клучна улога во промовирањето на [здравствената] свест и управувањето со животната средина. Училиштата можат да инкорпорираат наставни програми што ги учат учениците за важноста на балансираната исхрана, редовното вежбање и влијанието на човековите активности врз [животната средина]. Овој холистички пристап гарантира дека младите луѓе растат со добро заокружено разбирање за тоа како нивните постапки влијаат и на нивното лично [здравје] и на планетата.

Понатаму, заедниците можат да имаат корист од иницијативи што комбинираат [образовни] и [еколошки] проекти, како што се заеднички градини или програми за рециклирање. Овие активности не само што обезбедуваат практично [образование], туку и поттикнуваат чувство на одговорност и заеднички дух. Со вклучување на жителите во овие напори, заедниците можат да изградат поодржлива и поздрава средина за сите. Покрај тоа, пристапот до квалитетни [здравствени] услуги и образовни ресурси може значително да ја подобри целокупната благосостојба на членовите на заедницата, создавајќи позитивен циклус на подобрување во сите три области.

За да се постигнат овие цели, важно е локалните лидери и организации да соработуваат и да создаваат сеопфатни планови што се однесуваат на меѓусебно поврзаниот карактер на [здравјето], [образованието] и [животната средина]. Со заедничка работа, тие можат да развијат програми и политики што го поддржуваат долгорочното [образование] и [здравјето] на заедницата, а истовремено ја заштитуваат и подобруваат [животната средина]. Овој колаборативен пристап гарантира дека заедницата напредува на одржлив и хармоничен начин.

Образовните институции играат клучна улога во овој процес, служејќи како центри за информации и иновации. Тие можат да соработуваат со локалните бизниси и владини агенции за да создадат пракси, работилници и програми за обука што ги опремуваат жителите со вештини потребни за справување со предизвиците [во животната средина] и промовирање на [здравствени] иницијативи. На овој начин, [образованието] станува моќна алатка за поттикнување позитивни промени и градење отпорна заедница.

Општо земено, интеграцијата на [здравствените], [образовните] и [еколошките] иницијативи е клучна за долгорочниот успех и благосостојба на секоја заедница. Со негување култура на учење и еколошка свест, заедниците можат да создадат подобра ид This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Кои се клучните карактеристики на [производ] што го издвојуваат на пазарот? Вашиот одговор треба да содржи најмалку 3 места претставени со квадратни загради, како на пример [производ]. Вашиот одговор мора да содржи наслов, завиткан во двојни аголни загради, како на пример <<Клучни карактеристики на [производ]>>. Целиот ваш одговор треба да биде на англиски јазик и со мали букви. Не се дозволени големи букви. Вклучете клучни зборови [иновативен, конкурентен, технологија, функционалност, дизајн] во одговорот. Во вашиот одговор, зборот [производ] треба да се појави најмалку 4 пати. Одговорете со најмалку 200 зборови.

<<клучни карактеристики на [производ]>>

[производ] се издвојува на пазарот поради својот иновативен пристап кон [технологијата] и [функционалноста]. Дизајнот на [производ] не е само естетски пријатен, туку и многу практичен, што го прави врвен избор за потрошувачите кои бараат [конкурентска] предност. Една од клучните карактеристики што го издвојува [производ] е неговата напредна технологија, која беспрекорно се интегрира со постојните системи за подобрување на перформансите и ефикасноста. Оваа иновативна технологија му овозможува на [производ] да испорача супериорни резултати во споредба со многу од неговите конкуренти.

Друга извонредна карактеристика на [производ] е неговиот лесен за користење дизајн. Интуитивниот интерфејс и елегантната естетика им олеснуваат на корисниците да се движат и да ги користат сите функции без никакви проблеми. Без разлика дали сте технолошки искусен поединец или сте нови на пазарот, [производ] гарантира дека можете веднаш да уживате во неговите придобивки. Фокусот на корисничкото искуство е очигледен во секој аспект на [производ], од процесот на поставување до неговата секојдневна употреба.

Дополнително, [производ] нуди широк спектар на функционалности кои ги задоволуваат различните потреби. Од основни функции до напредни опции, [производ] обезбедува сеопфатно решение кое може да се прилагоди на различни сценарија. Оваа разновидност го прави [производ] одличен избор и за лична и за професионална употреба. Можноста за прилагодување на поставките и преференциите дополнително го подобрува корисничкото искуство, овозможувајќи ви да го прилагодите [производот] на вашите специфични барања.

Накратко, [производ] се издвојува на пазарот благодарение на својата иновативна технологија, конкурентен дизајн и робусна функционалност. Овие клучни карактеристики го прават [product] избор за секој што сака да го подобри своето искуство и да постигне подобри резултати. Без разлика дали барате сигурно, ефикасно или стилско решение, [product] испорачува на сите фронтови.

[product] продолжува да ги поместува границите на она што е можно на пазарот, поставувајќи нови стандарди за перформанси и задоволство на корисниците. Со својата најсовремена технологија и внимателно осмислен дизајн, [product] е подготвен да остане лидер во индустријата во годините што доаѓаат.

Комбинацијата од иновативна технологија, конкурентен дизајн и напредна функционалност го прави [product] извонреден избор на пазарот. Без разлика дали сте професионален или обичен корисник, [product] нуди убедливо решение што може да ги исполни и надмине вашите This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Кои се клучните карактеристики на успешна мобилна апликација и како овие функции можат да се интегрираат во нова апликација за да се обезбеди нејзин успех? Вашиот одговор треба да содржи најмалку 3 точки за означување. Користете ги точките за означување како што се: * Ова е точка 1. Означете најмалку 2 дела во вашиот одговор со означување, т.е. *означен дел*. Треба да има 2 пасуси. Пасусите се одделени со делител за означување: ***
***
*Успешна мобилна апликација е онаа што не само што ги задоволува потребите на своите корисници, туку и се издвојува на преполн пазар.* За да се постигне ова, неколку клучни функции мора да бидат вклучени во дизајнот и функционалноста на апликацијата. Овие функции се неопходни за ангажманот, задржувањето на корисниците и целокупното задоволство. Со фокусирање на овие елементи, програмерите можат да создадат мобилна апликација што резонира со нејзината целна публика и постигнува долгорочен успех.

* *Лесен интерфејс за користење*: Добро дизајнираниот кориснички интерфејс (UI) е клучен за успешна мобилна апликација. Корисничкиот интерфејс треба да биде интуитивен и лесен за навигација, осигурувајќи дека корисниците можат брзо да го пронајдат она што им е потребно без да се чувствуваат преоптоварени. Ова може да се постигне преку чист распоред, конзистентни елементи на дизајнот и прилагодливи интеракции. *Истакнувајќи ги повратните информации од корисниците*: Редовното собирање и имплементирање на повратни информации од корисниците може да помогне во усовршувањето на корисничкиот интерфејс и решавањето на сите проблеми, што доведува до подобро корисничко искуство.
***
* *Беспрекорни перформанси*: Перформансите се уште еден клучен фактор за успехот на мобилната апликација. Апликацијата треба да се вчитува брзо, да работи непречено и да се справува со голем број корисници без падови или застој. Оптимизирањето на кодот, намалувањето на големината на датотеките и користењето ефикасни структури на податоци се некои стратегии за подобрување на перформансите. *Истакнувајќи ја важноста на тестирањето*: Темелното тестирање, вклучувајќи тестирање на оптоварувањето и тестирање на стрес, може да помогне во идентификувањето и решавањето на проблемите со перформансите пред да се стартува апликацијата.
* *Антактивни и вредни функции*: За да се вратат корисниците, апликацијата мора да понуди функции што обезбедуваат вистинска вредност. Ова може да вклучува персонализирана содржина, споделување на социјалните мрежи, гамификација и редовни ажурирања со нова содржина или функционалности. Функциите што се усогласуваат со основната намена на апликацијата и го подобруваат корисничкото искуство можат значително да го зголемат ангажманот и задржувањето на корисниците.
* *Безбедност и приватност*: Со зголемената загриженост за приватноста на податоците, корисниците имаат поголема веројатност да веруваат и да користат апликации што ја сфаќаат безбедноста сериозно. Спроведувањето робусни безбедносни мерки, како што се енкрипција, безбедна ав This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(

KeyboardInterrupt:

# Continue Training Model From Checkpoint

In [12]:
trainer.train(resume_from_checkpoint=True)

c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Вашиот одговор треба да содржи најмалку 200 зборови. Вашиот одговор мора да има 4 пасуси. Пасусите се одделени со ознака за ознаки: ***

Вашиот одговор мора да содржи наслов, завиткан во двојни аголни загради, како на пример <<Разбирање на основите на машинското учење>>.

Вашиот одговор мора да содржи постскриптум што започнува со PS

Целиот ваш одговор треба да биде на англиски јазик и со сите мали букви. Не се дозволени големи букви.

Во вашиот одговор, зборот „алгоритам“ треба да се појави најмалку 5 пати.

Во вашиот одговор, буквата „l“ треба да се појави најмалку 10 пати.

Вашиот одговор треба да ги објасни основите на машинското учење на едноставен и разбирлив начин за почетници.

<<разбирање на основите на машинското учење>>

Машинското учење е подмножество на вештачката интелигенција што се фокусира на градење системи што можат да учат од податоци и да донесуваат предвидувања или одлуки без да бидат експлицитно програмирани. Основната идеја зад машинското учење е да се развијат алгоритми што можат да ги подобрат своите перформанси со текот на времето преку учење од искуство. Овие алгоритми користат статистички техники за да идентификуваат шеми во големи бази на податоци и да прават предвидувања врз основа на тие шеми. На пример, алгоритам за машинско учење може да биде обучен да препознава слики од мачки со анализа на илјадници слики од мачки и идентификување на заеднички карактеристики.

***

една од клучните предности на машинското учење е неговата способност да се справува со сложени и големи бази на податоци. Традиционалните пристапи кон програмирање честопати се мачат со вакви податоци, но алгоритмите за машинско учење можат да ги обработуваат и да ги разберат. Процесот на учење вклучува хранење на алгоритмот со означени податоци, каде што се познати точните одговори, и дозволување да ги прилагоди своите параметри за да ги минимизира грешките. Со текот на времето, алгоритмот станува попрецизен во своите предвидувања или класификации. Овој процес на учење може да биде надгледуван, ненадгледуван или полунадгледуван, во зависност од видот и достапноста на податоците.

***

друг важен концепт во машинското учење е моделот. Моделот е резултат на процесот на обука и го претставува наученото знаење. Моделите можат да бидат едноставни, како линеарна регресија или сложени, како длабоки невронски мрежи. Изборот на модел зависи од специфичниот проблем и природата на податоците. Откако ќе се обучи моделот, тој може да се користи за давање предвидувања врз основа на нови, невидени податоци. На пример, модел обучен да ги предвиди цените на домувањето врз основа на карактеристики како што се локација, големина и број на спални соби може да се користи за проценка на цената на нова куќа.

***

Машинското учење има широк спектар на апликации, од системи за препораки во е-трговијата до автономни возила и дијагностика во здравствената заштита. Како што полето продолжува да се развива, се развиваат нови алгоритми и техники за справување со уште посложени проблеми. Разбирањето на основите на машинското учење е клучно за секој што е заинтересиран за технологијата, бидејќи таа ја формира основата за многу од напредоците што ги гледа This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Би сакал/а да напишете кратка приказна за изгубен прстен. Погрижете се приказната да има јасен почеток, средина и крај. Приказната треба да биде раскажана во прво лице и да биде долга најмалку 500 зборови. Ве молам, погрижете се зборот „прстен“ да се појавува најмалку 10 пати во приказната. Исто така, приказната треба да има морална поука на крајот. Конечно, приказната треба да биде форматирана со наслов и три дела означени со „ДЕЛ 1“, „ДЕЛ 2“ и „ДЕЛ 3“.

<<Изгубениот прстен>>

ДЕЛ 1
Беше студено есенско утро кога решив да прошетам во блискиот парк. Сонцето штотуку почнуваше да изгрева, фрлајќи топол сјај врз тревата покриена со роса. Немав посебна дестинација на ум, само желба да ја разбистам главата и да уживам во раниот утрински мир. Додека шетав по кривулестите патеки, забележав мал зрак светлина во тревата. Љубопитен, се наведнав да истражам и најдов прекрасен сребрен прстен. Прстенот беше сложено дизајниран со нежни гравури и мал, светкав скапоцен камен. Беше јасно дека овој прстен е од значајна вредност и сентиментално значење за неговиот сопственик.

Земајќи го прстенот, почувствував мешавина од возбуда и загриженост. Знаев дека морам да го пронајдам вистинскиот сопственик, но предизвикот беше од каде да почнам. Се огледав низ паркот, надевајќи се дека ќе забележам некој што можеби е вознемирен од грижа за својот изгубен имот. Сепак, паркот беше сè уште релативно празен во тоа време и не можев да видам никој што изгледаше како да го изгубил прстенот.

ДЕЛ 2
Решив да го земам прстенот дома и да размислам за моите следни чекори. Откако се вратив во мојот стан, го испитав прстенот подетално. Скапоцениот камен беше темно син, речиси како бојата на ведро небо во сончев ден. Гравурите на прстенот беа толку детални што речиси како да раскажуваа приказна. Се прашував за лицето кое го поседуваше овој прстен. Дали беше семеен реликви? Подарок од близок? Помислата дека некој го бара ова изгубено богатство ме трогна во срцето.

Решена да помогнам, објавив слика од прстенот на социјалните мрежи и во локалните групи во заедницата. Исто така, испечатив флаери и ги поставив низ паркот и околните области. Поминаа денови и добив неколку пораки од луѓе кои тврдеа дека изгубиле прстен, но ниедна не се совпаѓаше со описот на оној што го најдов.

Една вечер, додека седев во дневната соба, мојот телефон заѕвони со порака. Беше од жена по име Емили. Таа го опиша прстенот со толку живописни детали што знаев дека таа е законскиот сопственик. Се договорив да се сретнам со неа во паркот следниот ден за да го вратам прстенот.

ДЕЛ 3
Следното утро, ја сретнав Емили во паркот. Таа беше нежна, добронамерна жена со топла насмевка. Кога ѝ го подадов прстенот, нејзините очи се наполнија со солзи. Таа објасни дека прстенот ѝ припаѓал на нејзината баба, која ѝ го предала како This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Вашиот одговор треба да биде на англиски јазик и со мали букви. Не се дозволени големи букви. Вашиот одговор треба да содржи најмалку 5 заменски резервирани места претставени со квадратни загради, како на пример [адреса]. Вашиот одговор треба да биде долг најмалку 150 зборови. Вклучете ги клучните зборови [интернет, безбедност, приватност, податоци, енкрипција] во одговорот. Во вашиот одговор, зборот приватност треба да се појави најмалку 3 пати. Означете најмалку 2 дела во вашиот одговор со markdown, т.е. *означен дел*. ***

Загрижен сум за *приватноста* на моите податоци при користење на интернет. Кои мерки можам да преземам за да ја обезбедам мојата *приватност* и *безбедност* на интернет? Како можам да ги заштитам моите *податоци* додека пребарувам и користам разни онлајн услуги? Каква улога игра *енкрипцијата* во безбедноста на моите информации? [first_name] [last_name] [email] [phone_number] [address]
***

[response]
***
„Ги разбирам вашите загрижености во врска со *приватноста* и *безбедноста* при користење на интернет. Еве неколку мерки што можете да ги преземете за да ја заштитите вашата *приватност* и *податоци*:

* *користење силни и уникатни лозинки*: ова е еден од наједноставните, но најефикасните начини за подобрување на вашата онлајн *безбедност*. Осигурајте се дека користите различни лозинки за секоја сметка и размислете за користење на менаџер за лозинки за да ги следите.

* *овозможување двофакторска автентикација (2fa)*: 2fa додава дополнителен слој на *безбедност* со тоа што бара втора форма на верификација покрај вашата лозинка. Ова може да биде код испратен на вашиот телефон или апликација за автентикација.

* *користење виртуелна приватна мрежа (vpn)*: vpn го шифрира вашиот интернет сообраќај и ја крие вашата IP адреса, отежнувајќи им на другите да ги следат вашите онлајн активности и да ја компромитираат вашата *приватност*.

* *одржување на вашиот софтвер ажуриран*: редовно ажурирајте го вашиот оперативен систем, веб-прелистувачот и друг софтвер за да се осигурате дека ги имате најновите *безбедносни* закрпи и функции.

* *внимателно со личните информации*: бидете внимателни какви информации споделувате онлајн, особено на платформите на социјалните медиуми. избегнувајте јавно споделување чувствителни детали како вашата [адреса] или [телефонски_број].[BR]]
*енкрипцијата* игра клучна улога во безбедноста на вашите информации. ги претвора вашите податоци во кодирана форма што може да се дешифрира само со специфичен клуч. Ова значи дека дури и ако некој ги пресретне вашите податоци, нема да може да ги прочита без клучот. многу веб-страници и услуги користат *енкрипција* за да ја заштитат вашата *приватност* и *податоци* за време на преносот.

доколку имате дополнителни прашања, слободно контактирајте ме на [е-пошта]. Се надевам дека ова ви помага да се чувствувате побезбедно додека го користите интернет."

ps останете безбедни онлајн, [first_name] [last_name]!
"<end_of_turn>
<start_of_turn>model This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Вашиот одговор треба да содржи најмалку 300 зборови. Во вашиот одговор, зборот „иновација“ треба да се појави најмалку 5 пати. Вашиот одговор мора да содржи наслов, завиткан во двојни аголни загради, како на пример <<Улогата на иновациите во современиот бизнис>>. Означете најмалку 3 делови во вашиот одговор со markdown, т.е. *означен дел*. ***

Во брзиот свет на современиот бизнис, како иновациите играат клучна улога во успехот и одржливоста на компаниите?
***
<<Улогата на иновациите во современиот бизнис>>

Во брзиот свет на современиот бизнис, *иновацијата* претставува камен-темелник за успехот и одржливоста на компаниите. Способноста за прилагодување и еволуција повеќе не е само предност; таа стана неопходност. Компаниите кои не успеваат да иновираат ризикуваат да станат застарени на пазар каде што преференциите на потрошувачите и технолошкиот напредок постојано се менуваат.

*Иновацијата* го поттикнува растот со тоа што им овозможува на компаниите да развиваат нови производи и услуги што ги задоволуваат потребите на новите пазари. На пример, подемот на е-трговијата ги принуди традиционалните трговци на мало со физичка локација да воведуваат иновации во своите бизнис модели за да останат конкурентни. Со прифаќање на дигиталните технологии и нудење беспрекорни искуства за онлајн купување, овие трговци на мало можат да привлечат поширока база на клиенти и да го зголемат својот пазарен удел.

Покрај тоа, *иновацијата* поттикнува култура на континуирано подобрување во рамките на организациите. Компаниите кои даваат приоритет на иновациите ги охрабруваат своите вработени да размислуваат креативно и да го предизвикаат статус кво. Овој начин на размислување може да доведе до револуционерни идеи кои не само што ги подобруваат постојните производи, туку и отвораат сосема нови пазари. На пример, развојот на технологии за обновлива енергија не само што им помогна на компаниите да го намалат своето влијание врз животната средина, туку создаде и нови деловни можности во зелената економија.

*Иновацијата*, исто така, игра клучна улога во управувањето со ризици. Со тоа што остануваат чекор понапред од трендовите во индустријата и проактивно се справуваат со потенцијалните предизвици, компаниите можат да ги ублажат ризиците и да одржат конкурентска предност. На пример, автомобилската индустрија беше принудена да воведува иновации како одговор на загриженоста за климатските промени и недостигот на ресурси. Развојот на електрични и автономни возила не само што ги реши овие проблеми, туку отвори и нови патишта за раст и експанзија.

На крајот на краиштата, *иновацијата* не е само опстанок; туку и просперитет во брзо менувачки деловен пејзаж. Компаниите кои ја прифаќаат иновацијата како клучен дел од нивната стратегија се во подобра позиција да ги искористат новите можности и да изградат одржлива иднина. Без разлика дали преку развој на производи, подобрување на процесите или трансформација на бизнис моделот, *иновацијата* е клучот за долгорочен успех во современиот деловен свет.

*Иновацијата* не е еднократен настан This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Дајте детално објаснување за карактеристиките и придобивките на паметниот часовник. Вашиот одговор мора да содржи наслов, завиткан во двојни аголни загради, како на пример <<поема на радоста>>. Вашиот одговор треба да содржи најмалку 4 резервирани места претставени со квадратни загради, како на пример [адреса]. Означете најмалку 2 дела во вашиот одговор со markdown, т.е. *означен дел*. Треба да има 3 пасуси. Пасусите се одделени со делител за markdown: ***

<<Карактеристики и придобивки на паметниот часовник>>

*Паметните часовници значително еволуираа со текот на годините, нудејќи широк спектар на функции и придобивки што го подобруваат секојдневниот живот.* Овие уреди не се само едноставни мерачи на време, туку се моќни алатки што беспрекорно се интегрираат со вашиот паметен телефон и други паметни уреди. Една од основните карактеристики на паметниот часовник е неговата способност да ве известува за важни известувања и пораки. Без разлика дали станува збор за повик, СМС-порака, е-пошта или известување од социјалните медиуми, можете да останете поврзани без постојано да го проверувате телефонот. Дополнително, паметните часовници често доаѓаат со вградени тракери за здравје и фитнес, што ви овозможува да го следите вашиот пулс, да ги следите вашите чекори, па дури и да ги анализирате вашите навики за спиење. Некои модели дури нудат и напредни функции како GPS следење, репродукција на музика и мобилни плаќања, што ги прави разновидни придружници и за работа и за забава.

***

*Придобивките од паметниот часовник се протегаат подалеку од само практичноста и поврзаноста.* *На пример, можностите за следење на здравјето и фитнесот можат да ве мотивираат да одржувате активен животен стил и да ја подобрите вашата целокупна благосостојба.* Со поставување цели и следење на вашиот напредок, можете да останете во тек со вашите здравствени метрики и да донесувате информирани одлуки за вашата исхрана и рутини за вежбање. Покрај тоа, можноста за контрола на паметни домашни уреди и примање известувања на вашиот зглоб може да ја подобри вашата безбедност дома. На пример, можете да добивате известувања ако безбедносната камера открие необична активност или ако се вклучи паметен детектор за чад. Оваа непосредна повратна информација може да биде клучна во итни случаи, овозможувајќи ви брзо да дејствувате.

***

*Паметните часовници исто така нудат ниво на персонализација и стил што може да го надополни вашето чувство за мода.* Многу паметни часовници доаѓаат со заменливи ленти и прилагодливи изгледи на часовникот, така што можете да го усогласите вашиот уред со вашата облека или расположение. Некои дури нудат и луксузни дизајни со премиум материјали како што се не'рѓосувачки челик и кожа, што ги прави погодни за формални пригоди. Понатаму, интеграцијата со гласовни асистенти како [гласовен_асистент] и можноста за контрола на паметни домашни уреди како [smart_light] и [smart_lock] можат да ги поедностават вашите дневни рутини и да го направат вашиот дом поефикасен. Без разлика дали сте технолошки ентузијаст, фитнес љубител или некој што ја цени практичноста и стилот, паметниот часовник може да би This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.
  warnings.warn(
c:\Users\stefv\anaconda3\envs\train_env\lib\site-packages\trl\trainer\utils.py:160: UserWarning: Could not find response key `<start_of_turn>model
` in the following instance: <bos><bos><start_of_turn>user
Ми треба детален одговор за придобивките од користењето визуелни помагала во презентациите. Вашиот одговор треба да содржи најмалку 500 зборови, а зборот „визуелен“ треба да се појави најмалку 10 пати. Дополнително, вашиот одговор мора да содржи наслов, завиткан во двојни аголни загради, како на пример <<придобивки од визуелните помагала во презентациите>>. Завршете го вашиот одговор со токму оваа фраза: „Дали има нешто друго со што можам да помогнам?“

Ве молиме дадете добро структуриран одговор што ги опфаќа следниве точки:
- Објаснете како визуелните помагала можат да помогнат во задржувањето на информациите.
- Дискутирајте ја улогата на визуелните помагала во зголемувањето на ангажманот на публиката.
- Опишете го влијанието на визуелните помагала врз јасноста на презентацијата.
- Истакнете ја важноста на визуелните помагала во правењето на сложените информации поразбирливи.
- Наведете примери за ефикасни визуелни помагала.

<<придобивки од визуелните помагала во презентациите>>

Визуелните помагала играат клучна улога во подобрувањето на ефикасноста на презентациите со тоа што помагаат во задржувањето на информациите, го зголемуваат ангажманот на публиката, ја подобруваат јасноста и ги поедноставуваат сложените концепти. Еве детално истражување на овие придобивки:

***

Визуелните помагала значително го подобруваат задржувањето на информациите. Истражувањата покажаа дека луѓето имаат поголема веројатност да се сетат на информациите кога се презентирани визуелно, отколку само преку текст. Ова е затоа што визуелните стимули ангажираат повеќе делови од мозокот, правејќи ги информациите понезаборавни. На пример, користењето графикони, графикони и слики може да им помогне на членовите на публиката подобро да ги запомнат клучните точки и статистика. Визуелните помагала, исто така, обезбедуваат визуелна сидро што може да се потсети подоцна, зајакнувајќи го процесот на учење.

***

Визуелните помагала се инструментални за подобрување на ангажманот на публиката. Презентацијата што се потпира исклучиво на изговорени зборови или текст може брзо да стане монотона и да го изгуби вниманието на публиката. Визуелните елементи како што се слајдовите, видеата и демонстрациите можат да ја воодушеват публиката и да ја задржат заинтересирана. Овие помагала можат да предизвикаат емоции, да предизвикаат љубопитност и да создадат подинамична и интерактивна средина. Со ангажирање на повеќе сетила, визуелните помагала ја прават презентацијата попријатна и помалку е веројатно дека ќе биде заборавена.

***


TrainOutput(global_step=3169, training_loss=0.47867698254138374, metrics={'train_runtime': 28353.0713, 'train_samples_per_second': 1.788, 'train_steps_per_second': 0.112, 'total_flos': 8.71325621497198e+16, 'train_loss': 0.47867698254138374, 'epoch': 0.9999802780790848})

# Evaliation stage

In [26]:
dataset_path = r"./data/argilla-ifeval-like-data-fixed-mk-test.jsonl"


dataset_test = trainPipeline.get_dataset(dataset_path)

In [27]:
dataset_test = dataset_test.select(range(3))

In [28]:
dataset_test

Dataset({
    features: ['prompt', 'response'],
    num_rows: 3
})

In [29]:
dataset_test = dataset_test.map(trainPipeline.preprocess_function_sft)

In [30]:
dataset_test = dataset_test.select_columns(['messages'])

In [31]:
dataset_test

Dataset({
    features: ['messages'],
    num_rows: 3
})

In [ ]:
import torch

def evaluate_model_on_test(model, tokenizer, dataset, num_samples=3):
    model.eval()
    
    num_samples = min(num_samples, len(dataset))
    print(f"--- Evaluating {num_samples} Samples ---\n")

    for i in range(num_samples):
        messages = dataset[i]['messages']
        
        prompt_messages = [m for m in messages if m['role'] != 'assistant']
        ground_truth = next((m['content'] for m in reversed(messages) if m['role'] == 'assistant'), "No GT found")

       
        input_ids = tokenizer.apply_chat_template(
            prompt_messages, 
            tokenize=True, 
            add_generation_prompt=True, 
            return_tensors="pt"
        ).to(model.device) 
        
        
        with torch.no_grad():
            
            device_type = "cuda" if torch.cuda.is_available() else "cpu"
            with torch.autocast(device_type=device_type, dtype=model.dtype):
                output_ids = model.generate(
                    input_ids=input_ids,
                    max_new_tokens=512,
                    do_sample=True,
                    temperature=0.2,
                    top_p=0.9,
                    repetition_penalty=1.2,
                    eos_token_id=tokenizer.eos_token_id,
                )

        generated_tokens = output_ids[0][input_ids.shape[1]:]
        prediction_text = tokenizer.decode(generated_tokens, skip_special_tokens=True)

        print(f"SAMPLE {i+1}")
        print(f"PROMPT:\n{messages[0]['content'][:500]}")
        print("-" * 30)
        print(f"EXPECTED:\n{ground_truth[:500]}")
        print("-" * 30)
        print(f"GENERATED:\n{prediction_text}")
        print("\n" + "="*50 + "\n")


evaluate_model_on_test(model, tokenizer, dataset_test)

--- Evaluating 3 Samples ---

SAMPLE 1
PROMPT:
Во контекст на деловен состанок, дајте совети за ефикасна комуникација. Вашиот одговор мора да содржи наслов, завиткан во двојни аголни загради, како на пример <<песна на радоста>>. Вашиот одговор треба да содржи најмалку 5 реченици. Означете најмалку 2 дела во вашиот одговор со markdown, т.е. *означен дел*. На крајот од вашиот одговор, ве молиме експлицитно додадете постскриптум што започнува со PS
------------------------------
EXPECTED:
<<Совети за ефективна комуникација на деловни состаноци>>

Ефективната комуникација на деловните состаноци е клучна за постигнување на посакуваните резултати и одржување на професионална средина. *Прво, важно е да бидете јасни и концизни во вашата комуникација.* Ова значи директно да се премине на поентата и да се избегнува непотребен жаргон или сложен јазик што може да ги збуни учесниците. *Второ, активното слушање е клучно.* Обрнете внимание на она што го кажуваат другите и покажете дека слуша
------------------------------
GENERATED:
<<Ефективна комуникација во деловирано собрание>>

*За време на деловното собрание, важно е внимателно да се слуша и активно да се ангажменти.* Започнете со поставување јасни прашања или проблеми кои бараат внимание и подготвеност за дискусија. Користењето техники на активна аудио-забелување може значително да го подобри вашето разбирање и вклучување. Дополнително, користењето визуелни средства како точки или графички елементи може да помогне во пренесената информација и помага да се задржите сите заинтерерани. Конечно, осигурајте се дека имате јасен план за следење на процесот и донесување настани врз основа на она што сте ги споделиле, осигурувајќи се дека сите учесниците се усогласени и информирани. ПС Одвојувањето времичко за паузи за размислување и повратни информации може да биде неверојатен начин да се поттикнат продуктивни интеракции.
ПС Се надевам дека овие совети ќе му помогнат на вашите презентации и активности да остават привлечни и ефективни.
PS Не заборавајте континуирано да учите и прилагодувате на новите предизвикувања што можете да ги сретнете во бизнис срединото.

ps Проверете дали вашата комуникација е добро структурирана и лесно распорена за да избегнете недоразбиранија и да обезбедите непречено движење низ разговорот.

ПС Размислете за употреба на алатки како Zoom или Microsoft Teams за видео повиците и дигитални документи за да спречите физичката отстранување на лицата и да промовирате чувство на заедништво.

ПС Погрижете се да изберете единствена тема или фокус за да им дозволите на членовите на групата да се фокусираат на специфични области, намалувајќи го ризикот од нерелативно обврска.

ПС Во големите корпоратив

==================================================

SAMPLE 2
PROMPT:
Кои се клучните карактеристики на добро дизајнирана веб-страница? Вашиот одговор треба да содржи најмалку 3 резервирани места претставени со квадратни загради, како што е [адреса]. Вклучете ги клучните зборови [корисничко искуство], [навигација] и [одзивно дизајн] во одговорот. Вашиот одговор мора да содржи точно 3 точки за означување. Користете ги точките за означување како што се: * Ова е точка 1.
------------------------------
EXPECTED:
Добро дизајнираната веб-страница го дава приоритет на *корисничкото искуство*, осигурувајќи дека посетителите ја сметаат содржината за привлечна и лесна за користење. Ова вклучува интуитивна [навигација] и јасни копчиња за повикување на акција.
* [Респонсивниот дизајн] е клучен бидејќи ѝ овозможува на веб-страницата беспрекорно да се прилагодува на различни големини на екран и уреди. Ова осигурува дека корисниците имаат конзистентно искуство без разлика дали се на десктоп, таблет или паметен тел
------------------------------
GENERATED:
* Добро дизајнираната веб-страница обезбедува беспрекорна [навигација] која им олеснува на корисниците лесно да го проследат нивното движење низ страницата без никакви проблеми или губења на интерактивност.[BR]]
* Ефективната употреба на [одзивниот дизайн] гарантира дека страницата изгледа многу подобро на различни уреди, осигурувајќи дека корисниците можат непречено да ја користат вашата веб-страница на мобилни телефони, таблети и компјутери.[BR]]
* Јасна и привлечна [корисничка средина] помага да се задржи посетителите заинтересирани и ангажирани со вашето брендот, правејќи го процесот на конверзација поефикасен и подобар。[BR]]

Овие елементи работат заедно за да создадеат интуитивна и пријатна онлајн искуства што ја поддржат продуктивноста и лојалноста на клиентите. Запомнете, квалитетната веб-страница не само што ви помогне да постигнете вашите деловни цели, туку нуди и позитивно искуство за корисници.

ПС Се надевам дека оваа информација ќе ве води до прекрасни резултации! Доколку имате дополнителни прашања, слободно прашувате.

























































































==================================================

SAMPLE 3
PROMPT:
Вашиот одговор треба да содржи најмалку 3 реченици. Одговорот мора да содржи најмалку 2 заменски резервирани места претставени со квадратни загради, како на пример [адреса]. Означете најмалку 2 дела во вашиот одговор со markdown, т.е. *означен дел*. Во вашиот одговор, зборот *место* треба да се појави најмалку 2 пати.

Кои се некои важни фактори што треба да се земат предвид при избор на нов [дом] во [град]?
------------------------------
EXPECTED:
Кога избирате ново *место* што ќе го наречете дом во [град], треба да се земат предвид неколку важни фактори за да се осигурате дека ги задоволува вашите потреби и преференции. *Локацијата* е клучна, бидејќи влијае на вашето секојдневно патување до работа, пристапот до погодностите и целокупниот квалитет на живот. Дополнително, земете ја предвид безбедноста на соседството, состојбата на [домот] и трошоците за живот, што може значително да влијае на вашето долгорочно задоволство од вашето ново *м
------------------------------
GENERATED:
При избирање нов *[дом]* во *[град]*, важно е да земете предвид неколку клучни фактори кои можат значително да влијаат врз вашата целокупна среќа и удобност. Прво, разгледајте ја локацијата; топлото или ладното место може да го подобри квалитетот на животните на вашето ново *[домот]* и неговата близина до основните услуги како што се продавница за храна, болница и училишта. Второ, осигурајте се дека *[домовите]* имаат потребната просторија за вашите потреби, без оглед дали станува збор за спалница, куфер или работен простор. Конечно, не заборавајте да ги процените трошоците поврзани со живеењето во *[град],* вклучувајќи ги сите потенцијални трошоци за комунални услуги, осигурување и трошење на мапари.
ПС Секогаш проверувајте ги овие детали пред да направите окончателна одлука за да обезбедите непречено искуство со новото *[домот]* во *[град]*.[BR]]
PS Дополнете сè уште повеќе информации за конкретниот *[дом]* ако сте достапни!
ps Проверено: Запомнете, времето е суперен фактор во овој процес, затоа траен пристап е клучен.
Ps Дополнување: Нагласувам дека проценетите трошоци и условите на животното доматинството играат витална улога во решавањето на вашето решение за *[дом]* во *[град]*.[BR]]
ПС Секогаш проверете ги овие детали пред да направите окончателни одлуки за да обезбедете непречено искуство со новото *[домот]* во *[град]*.[BR]]
ПС Дополнувања: Не заборавајте да ги процените трошоците поврзани со живеењето во *[град],* вклучувајќи ги сите потенцијални трошоци за комунал

==================================================