In [1]:
import pandas as pd

In [10]:
df = pd.read_json("datasets/argilla-ifeval-like-data-fixed-mk.jsonl", lines=True, orient='records')

In [11]:
df.drop(columns=['key', 'instruction_id_list', 'kwargs', 'prompt_level_strict_acc', 'inst_level_strict_acc', 'prompt_level_loose_acc', 'inst_level_loose_acc'], inplace=True)

In [12]:
df.rename(columns={
    'prompt':'prompt_mk',
    'response':'response_mk',
    'prompt1':'prompt_en',
    'response1':'response_en',
}, inplace=True)

In [13]:
df

,prompt_mk,response_mk,prompt_en,response_en
0,Вашиот одговор треба да содржи најмалку 3 рече...,„Би рекол дека *првиот означен дел* ја воведув...,Your response should contain at least 3 senten...,"""i would say that the *first highlighted secti..."
1,Вашиот одговор треба да содржи најмалку 3 рече...,Иновацијата го поттикнува напредокот и ни пома...,Your response should contain at least 3 senten...,Innovation drives progress and helps us adapt ...
2,Ми треба креативен наслов за кратка приказна з...,<<Шепотења на волшебната шумичка>>,I need a creative title for a short story abou...,<<whispers of the enchanted grove>>
3,"Вашиот одговор мора да содржи наслов, завиткан...",<<Француската револуција: Пресвртница во истор...,"Your answer must contain a title, wrapped in d...",<<The French Revolution: A Turning Point in Hi...
4,Вашиот одговор треба да содржи најмалку 3 рече...,<<Разбирање на концептите на програмирање>>\n\...,Your response should contain at least 3 senten...,<<Understanding Programming Concepts>>\n\nProg...
...,...,...,...,...
56334,Кои се главните разлики помеѓу традиционалната...,Традиционалните куќи често се одликуваат со по...,What are the main differences between a tradit...,* Traditional houses often feature more ornate...
56335,Вашиот одговор треба да содржи најмалку 3 рече...,"Секако, можам да ви помогнам со тоа. Ве молам,...",Your response should contain at least 3 senten...,"Sure, I can assist you with that. Please provi..."
56336,Вашиот одговор треба да содржи најмалку 2 мест...,"Секако, можам да помогнам со тоа. Еве неколку ...",Your response should contain at least 2 placeh...,"sure, i can help with that. here are some opti..."
56337,Вашиот одговор треба да содржи најмалку 5 рече...,<<Пронаоѓање на вашиот пат>>\n\nЗа да ја прона...,Your response should contain at least 5 senten...,<<Finding Your Way>>\n\nTo find the location y...
56338,Вашиот одговор треба да содржи најмалку 5 рече...,Технологијата го револуционизираше начинот на ...,Your response should contain at least 5 senten...,Technology has revolutionized the way we live ...

In [16]:
df = df[['prompt_en', 'prompt_mk', 'response_en', 'response_mk']]

In [17]:
df

,prompt_en,prompt_mk,response_en,response_mk
0,Your response should contain at least 3 senten...,Вашиот одговор треба да содржи најмалку 3 рече...,"""i would say that the *first highlighted secti...",„Би рекол дека *првиот означен дел* ја воведув...
1,Your response should contain at least 3 senten...,Вашиот одговор треба да содржи најмалку 3 рече...,Innovation drives progress and helps us adapt ...,Иновацијата го поттикнува напредокот и ни пома...
2,I need a creative title for a short story abou...,Ми треба креативен наслов за кратка приказна з...,<<whispers of the enchanted grove>>,<<Шепотења на волшебната шумичка>>
3,"Your answer must contain a title, wrapped in d...","Вашиот одговор мора да содржи наслов, завиткан...",<<The French Revolution: A Turning Point in Hi...,<<Француската револуција: Пресвртница во истор...
4,Your response should contain at least 3 senten...,Вашиот одговор треба да содржи најмалку 3 рече...,<<Understanding Programming Concepts>>\n\nProg...,<<Разбирање на концептите на програмирање>>\n\...
...,...,...,...,...
56334,What are the main differences between a tradit...,Кои се главните разлики помеѓу традиционалната...,* Traditional houses often feature more ornate...,Традиционалните куќи често се одликуваат со по...
56335,Your response should contain at least 3 senten...,Вашиот одговор треба да содржи најмалку 3 рече...,"Sure, I can assist you with that. Please provi...","Секако, можам да ви помогнам со тоа. Ве молам,..."
56336,Your response should contain at least 2 placeh...,Вашиот одговор треба да содржи најмалку 2 мест...,"sure, i can help with that. here are some opti...","Секако, можам да помогнам со тоа. Еве неколку ..."
56337,Your response should contain at least 5 senten...,Вашиот одговор треба да содржи најмалку 5 рече...,<<Finding Your Way>>\n\nTo find the location y...,<<Пронаоѓање на вашиот пат>>\n\nЗа да ја прона...
56338,Your response should contain at least 5 senten...,Вашиот одговор треба да содржи најмалку 5 рече...,Technology has revolutionized the way we live ...,Технологијата го револуционизираше начинот на ...

In [19]:
grading_df = df.sample(10)

In [20]:
grading_df

,prompt_en,prompt_mk,response_en,response_mk
45657,Your response should contain at least 3 senten...,Вашиот одговор треба да содржи најмалку 3 рече...,"To send a package to [address] from [origin], ...",За да испратите пакет до [адреса] од [потекло]...
17052,Your response should contain less than 50 word...,Вашиот одговор треба да содржи помалку од 50 з...,"Sure, I can help with that. P.S. Is there anyt...","Секако, можам да помогнам со тоа. П.С. Дали им..."
31090,Your answer must contain exactly 3 bullet poin...,Вашиот одговор мора да содржи точно 3 точки. К...,* Point one is a concise statement that adhere...,* Првата точка е концизна изјава што се придрж...
36205,Provide a detailed explanation of the benefits...,Дајте детално објаснување за придобивките од к...,* *Enhanced Collaboration*: A CMS allows multi...,*Подобрена соработка*: CMS им овозможува на по...
9828,Your response should contain at least 3 senten...,Вашиот одговор треба да содржи најмалку 3 рече...,Effective time management techniques for remot...,Ефективните техники за управување со времето з...
7088,Provide a response to the following question: ...,Одговорете на следново прашање: Кои се придоби...,* A CRM system helps in *managing customer rel...,* CRM системот помага во *управувањето со одно...
36322,"Your entire response should be in English, and...",Целиот ваш одговор треба да биде на англиски ј...,<<sunshine and laughter>>\n\nin the warmth of ...,<<сончева светлина и смеа>>\n\nво топлината на...
51001,"What is the capital of France, and what are so...",Кој е главен град на Франција и кои се некои п...,"The capital of France is Paris, a city renowne...","Главен град на Франција е Париз, град познат п..."
42176,Your response should contain at least 3 senten...,Вашиот одговор треба да содржи најмалку 3 рече...,Sure I can adhere to those constraints. Here i...,Секако дека можам да се придржувам до тие огра...
26307,"Provide a response to the following query: ""Wh...",Дајте одговор на следново прашање: „Кои се при...,Using a cloud-based storage solution offers se...,Користењето решение за складирање базирано на ...

In [21]:
grading_df.to_json('translation_evaluation.json', orient='records', force_ascii=False, indent=2)